services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:1.0.0-beta.2
    container_name: portfolio
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - portfolio-data:/app/.data
    networks:
      - dokploy-network

volumes:
  portfolio-data:

networks:
  dokploy-network:
    external: true
